/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restoran_alstruk;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import java.util.LinkedList;
/**
 *  
 * @author Akhmad
 */
public class pesanMenu extends javax.swing.JFrame {
DefaultTableModel model,model1,model2;
    
    /**
     * Creates new form pesanMenu
     */
private int totalHarga;
private double diskonInt,totalSetelahDiskon;
  public pesanMenu() {
        initComponents();
        setLocationRelativeTo(this);
        harga.setVisible(false);
        hargaKirim.setVisible(false);
        diskon.setVisible(false);
        totalharga.setVisible(false);
        ongkir1.setVisible(false);
        ongkir.setVisible(false);
        labelHarga4.setVisible(false);
        uang.setVisible(false);
        String []table={"kd_pesanan","nama_pemesan","nama_menu","harga","Status"};
        model = new DefaultTableModel (table,0);
        String []listmenu={"KD Menu","Nama Menu","Harga"};
        model1 = new DefaultTableModel (listmenu,0);
        String []listAntrian={"Nama Pemesan","Nama Menu"};
        model2 = new DefaultTableModel (listAntrian,0);
        menuTable.setModel (model);
        menuTable1.setModel (model1);
        tblAntrian.setModel (model2);
        tampilkan();
        tampilkan1();
        tampilkan2();
    }
  
    
    double hitungDiskon(float totalHarga) {
        
        // Hitung diskon berdasarkan total_harga
        double diskon = 0;

        if (totalHarga >= 100000 && totalHarga < 150000 ) {
            diskon = totalHarga * 0.05f; // Diskon 5%
        } else if (totalHarga >= 150000 && totalHarga < 250000) {
            diskon = totalHarga * 0.1f; // Diskon 10%
        }else if (totalHarga >= 250000 && totalHarga < 300000) {
            diskon = totalHarga * 0.2f; // Diskon 20%
        }else if (totalHarga > 300000) {
            diskon = totalHarga * 0.3f; // Diskon 30%
        }
        return diskon;

    }

    double hitungTotalHarga(double totalHargaKirim, double diskon) {
        // Hitung total harga setelah diskon
        double totalSetelahDiskon = totalHargaKirim - diskon;

        return totalSetelahDiskon;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtHarga = new javax.swing.JTextField();
        cekNama = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        txtNamaMenu = new javax.swing.JTextField();
        txtPemesan = new javax.swing.JTextField();
        cekMenu = new javax.swing.JButton();
        tmbhPesanan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        menuTable = new javax.swing.JTable();
        diskon = new javax.swing.JLabel();
        labelHarga2 = new javax.swing.JLabel();
        harga = new javax.swing.JLabel();
        uang = new javax.swing.JTextField();
        labelHarga4 = new javax.swing.JLabel();
        bayarNow = new javax.swing.JButton();
        labelHarga = new javax.swing.JLabel();
        totalharga = new javax.swing.JLabel();
        labelHarga1 = new javax.swing.JLabel();
        txtJumlah = new javax.swing.JTextField();
        ongkir1 = new javax.swing.JLabel();
        ongkir = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        hargaKirim = new javax.swing.JLabel();
        labelHarga3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        menuTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        ongkir2 = new javax.swing.JLabel();
        labelHarga5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblAntrian = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 580, 70, 20));

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        txtHarga.setBorder(null);
        txtHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaActionPerformed(evt);
            }
        });
        getContentPane().add(txtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 469, 140, 20));

        cekNama.setBorder(null);
        cekNama.setContentAreaFilled(false);
        cekNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekNamaActionPerformed(evt);
            }
        });
        getContentPane().add(cekNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 540, 80, 20));
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 10, -1));

        txtNamaMenu.setBorder(null);
        txtNamaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaMenuActionPerformed(evt);
            }
        });
        txtNamaMenu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNamaMenuKeyReleased(evt);
            }
        });
        getContentPane().add(txtNamaMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 469, 140, 20));

        txtPemesan.setBorder(null);
        txtPemesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPemesanActionPerformed(evt);
            }
        });
        getContentPane().add(txtPemesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 540, 240, 29));

        cekMenu.setBorder(null);
        cekMenu.setContentAreaFilled(false);
        cekMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekMenuActionPerformed(evt);
            }
        });
        getContentPane().add(cekMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 470, 70, 20));

        tmbhPesanan.setBorder(null);
        tmbhPesanan.setContentAreaFilled(false);
        tmbhPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmbhPesananActionPerformed(evt);
            }
        });
        getContentPane().add(tmbhPesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 580, 70, 20));

        menuTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        menuTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(menuTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 370, 210));

        diskon.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        diskon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(diskon, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 450, 114, 22));

        labelHarga2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelHarga2.setForeground(new java.awt.Color(255, 255, 255));
        labelHarga2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHarga2.setText("JUMLAH");
        labelHarga2.setToolTipText("");
        getContentPane().add(labelHarga2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 510, 80, -1));

        harga.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        harga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, 63, 14));

        uang.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        uang.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        uang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uangActionPerformed(evt);
            }
        });
        getContentPane().add(uang, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 540, 114, -1));

        labelHarga4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelHarga4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHarga4.setText("UANG KAMU");
        labelHarga4.setToolTipText("");
        getContentPane().add(labelHarga4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 520, 97, -1));

        bayarNow.setText("BAYAR");
        bayarNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarNowActionPerformed(evt);
            }
        });
        getContentPane().add(bayarNow, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 590, -1, -1));

        labelHarga.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelHarga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHarga.setText("HARGA TOTAL");
        labelHarga.setToolTipText("");
        getContentPane().add(labelHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 360, 97, -1));

        totalharga.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        totalharga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(totalharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 500, 114, 20));

        labelHarga1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelHarga1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHarga1.setText("DISKON");
        labelHarga1.setToolTipText("");
        getContentPane().add(labelHarga1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 440, 97, -1));

        txtJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahActionPerformed(evt);
            }
        });
        getContentPane().add(txtJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, 80, 29));

        ongkir1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ongkir1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ongkir1.setText("incl.ONGKIR");
        ongkir1.setToolTipText("");
        getContentPane().add(ongkir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 380, 70, -1));

        ongkir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ongkir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ongkir.setText(" + Rp.10.000");
        ongkir.setToolTipText("");
        getContentPane().add(ongkir, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 380, 80, -1));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Montserrat Medium", 1, 12)); // NOI18N
        jLabel7.setText("ANTRIAN MENU DI DAPUR");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, -1, -1));

        hargaKirim.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        hargaKirim.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(hargaKirim, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 400, 114, 17));

        labelHarga3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelHarga3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHarga3.setText("HARGA AKHIR");
        labelHarga3.setToolTipText("");
        getContentPane().add(labelHarga3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 570, 97, -1));

        jLabel6.setFont(new java.awt.Font("Montserrat Medium", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("LIST MENU RESTORAN");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        menuTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        menuTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(menuTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 530, 99));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mainmenu.png"))); // NOI18N
        jLabel4.setText("jLabel3");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 580, 100, 30));

        ongkir2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ongkir2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ongkir2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pemesanan.png"))); // NOI18N
        ongkir2.setToolTipText("");
        getContentPane().add(ongkir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, -1));

        labelHarga5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelHarga5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHarga5.setText("HARGA AKHIR");
        labelHarga5.setToolTipText("");
        getContentPane().add(labelHarga5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 480, 97, -1));

        tblAntrian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblAntrian);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 190, 270));

        jButton3.setText("Pesanan Siap!!");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 310, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cekMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekMenuActionPerformed
        // TODO add your handling code here:       
        try {
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/restoran","root","");
            Statement state = con.createStatement();
            ResultSet rs = state.executeQuery("Select * from menu" + " where nama_menu like('%"+txtNamaMenu.getText()+"%')");
            if (rs.next()) {
                cekMenu.setEnabled(true);
                txtID.setText(rs.getString("kd_menu"));
                txtNamaMenu.setText(rs.getString("nama_menu"));
                txtHarga.setText(rs.getString("harga"));
            } else {
                JOptionPane.showMessageDialog(this,"Nama:Salah", "Informasi",JOptionPane.INFORMATION_MESSAGE);
                cekMenu.setEnabled(false);
                txtID.requestFocus();
                txtNamaMenu.setText("");
                txtHarga.setText("");
            }
        }
        catch (SQLException e){
            System.out.println("Koneksi DB Gagal!! " + e.toString());
        }
    }//GEN-LAST:event_cekMenuActionPerformed

    private void txtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        new mainmenu().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtNamaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaMenuActionPerformed

    private void txtPemesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPemesanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPemesanActionPerformed

    private void tmbhPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbhPesananActionPerformed
        // TODO add your handling code here:
       try {
            if(txtNamaMenu.getText().equals("") ||
            txtHarga.getText().equals("") ||
            txtPemesan.getText().equals("")){   
                JOptionPane.showMessageDialog(this, "Data Tidak Boleh Kosong", "Pesan", JOptionPane.ERROR_MESSAGE);
                clear();
            }else{
                        Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/restoran","root","");
        PreparedStatement pStatement =
        con.prepareStatement("INSERT INTO log_pesan (nama_pemesan, menu , jumlah, harga, status) VALUES (?,?,?,?,?)");
        
        pStatement.setString(1, txtPemesan.getText());
        pStatement.setString(2, txtNamaMenu.getText()); 
        pStatement.setString(3, txtJumlah.getText());
        int totHarga = Integer.parseInt(txtHarga.getText()) * Integer.parseInt(txtJumlah.getText());
        pStatement.setInt(4, totHarga);
        pStatement.setString(5, "Di Dapur");
        
        if (pStatement.executeUpdate()>0)
            JOptionPane.showMessageDialog(this,
            "Penambahan sukses", "Informasi",
            JOptionPane.INFORMATION_MESSAGE);
        else
            JOptionPane.showMessageDialog(this,
            "Penambahan gagal", "Informasi",
            JOptionPane.INFORMATION_MESSAGE);

        pStatement.close();
        con.close();
        txtNamaMenu.setText("");
        txtHarga.setText("");
        txtJumlah.setText("");

        this.dispose();
        new pesanMenu().setVisible(true);
            }
        }
        catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());
        }
    }//GEN-LAST:event_tmbhPesananActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new pesanMenu().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cekNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekNamaActionPerformed
        // TODO add your handling code here:
       
        int row = menuTable.getRowCount();
            for(int a=0; a<row; a++){
                model.removeRow(0);
            }
        try {
            Connection cn= (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/restoran","root","");
            ResultSet rs = cn.createStatement().executeQuery("SELECT * from log_pesan where nama_pemesan like '%"+txtPemesan.getText()+"%'");

            while (rs.next()){
                String data[]={rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(5),rs.getString(6)};
                model.addRow(data);
            }
            totalHarga = 0;
            String nama = null;
            
            ResultSet res = cn.createStatement().executeQuery("SELECT SUM(harga) as total_harga from log_pesan where nama_pemesan like '%"+txtPemesan.getText()+"%'");
            
            while (res.next()){                 
                totalHarga = Integer.parseInt(res.getString("total_harga"));
            }
            int TotalHargaKirim = totalHarga + 10000; // Anggap biaya pengiriman tetap

            diskonInt = hitungDiskon((float)TotalHargaKirim);
            totalSetelahDiskon = hitungTotalHarga(TotalHargaKirim, diskonInt);

            harga.setText("Rp."+String.valueOf(totalHarga));
            hargaKirim.setText("Rp."+String.valueOf(TotalHargaKirim));
            diskon.setText("Rp."+String.valueOf(diskonInt));
            totalharga.setText("Rp."+String.valueOf(totalSetelahDiskon));
            harga.setVisible(true);
            hargaKirim.setVisible(true);
            diskon.setVisible(true);
            ongkir1.setVisible(true);
            ongkir.setVisible(true);
            totalharga.setVisible(true);
            labelHarga4.setVisible(true);
            uang.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(pesanMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_cekNamaActionPerformed

    private void uangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uangActionPerformed

    private void txtJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahActionPerformed

    private void txtNamaMenuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaMenuKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaMenuKeyReleased

    private void menuTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuTable1MouseClicked
        // TODO add your handling code here:
        int i =menuTable1.getSelectedRow();
        if (i>-1){
            txtID.setText(model1.getValueAt (i,0).toString());
            txtNamaMenu.setText(model1.getValueAt (i,1).toString());
            txtHarga.setText (model1.getValueAt (i,2).toString());
        }
    }//GEN-LAST:event_menuTable1MouseClicked

    private void bayarNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarNowActionPerformed
        // TODO add your handling code here:
        int duit = Integer.parseInt(uang.getText());

        // Cek status pesanan
        try {
            Connection cn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/restoran", "root", "");
            Statement st = cn.createStatement();

            String sql = "SELECT * FROM log_pesan WHERE nama_pemesan = '" + txtPemesan.getText() + "'";
            ResultSet rs = st.executeQuery(sql);

            if (rs.next()) {
                String status = rs.getString("status");

                if (status.equals("Di Dapur")) {
                    // Tampilkan notif pesanan masih di dapur
                    JOptionPane.showMessageDialog(this, "Harap menunggu, Pesanan anda masih kami proses...", "Peringatan", JOptionPane.WARNING_MESSAGE);

                    // Kembali ke menu pesan
                    this.dispose();
                    new pesanMenu().setVisible(true);

                } else{
                    // Jika status pesanan sudah bukan "Di Dapur", maka lanjutkan ke proses pembayaran
                    if (duit >= totalSetelahDiskon && !status.equals("Di Dapur")) {
                        double kembalian = duit - totalSetelahDiskon;

                        // Hapus seluruh pesanan dengan nama_pemesan yang sama
                        try {
                            cn.createStatement().executeUpdate("DELETE FROM log_pesan WHERE nama_pemesan = '" + txtPemesan.getText() + "'");
                        } catch (SQLException ex) {
                            Logger.getLogger(pesanMenu.class.getName()).log(Level.SEVERE, null, ex);
                        }

                        // Tampilkan notif pembayaran berhasil
                        JOptionPane.showMessageDialog(this,
                                "Terimakasih, " + txtPemesan.getText() + " atas pemesanannya!! Anda membayar Rp." + duit + " dan Kembalian Rp." + kembalian, "Informasi",
                                JOptionPane.INFORMATION_MESSAGE);

                        // Kembali ke menu pesan
                        this.dispose();
                        new pesanMenu().setVisible(true);
                    } else {
                        // Tampilkan notif uang tidak mencukupi
                        JOptionPane.showMessageDialog(this, "Uang tidak mencukupi", "Peringatan", JOptionPane.WARNING_MESSAGE);

                        // Kembali ke menu pesan
                        this.dispose();
                        new pesanMenu().setVisible(true);
                    }                    
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(pesanMenu.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_bayarNowActionPerformed

    private void menuTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuTableMouseClicked
        // TODO add your handling code here:
                // TODO add your handling code here:
        int i =menuTable.getSelectedRow();
        if (i>-1){
            txtPemesan.setText(model.getValueAt (i,1).toString());
        }
    }//GEN-LAST:event_menuTableMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
            try {
        Connection cn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/restoran", "root", "");
        Statement st = cn.createStatement();

        // Ambil data pesanan dengan status "Di Dapur" dan id terkecil
        String sql = "SELECT * FROM log_pesan WHERE status='Di Dapur' ORDER BY kd_pesanan ASC LIMIT 1";
        ResultSet rs = st.executeQuery(sql);

        // Jika ada data
        if (rs.next()) {

            // Tampilkan notifikasi
            String nama_pemesan = rs.getString("nama_pemesan");
            JOptionPane.showMessageDialog(this,
            "Pesanan atas nama "+nama_pemesan+" siap untuk diantarkan!!", "Informasi",
            JOptionPane.INFORMATION_MESSAGE);
            // Ubah status pesanan
            String kd_pesanan = rs.getString("kd_pesanan");
            String status = "Siap Dikirim";
            st.executeUpdate("UPDATE log_pesan SET status='" + status + "' WHERE kd_pesanan='" + kd_pesanan + "'");

        } else {
            // Tidak ada data yang ditemukan
            JOptionPane.showMessageDialog(null, "Tidak ada pesanan dengan status 'Di Dapur'");
        }
        this.dispose();
        new pesanMenu().setVisible(true);
    } catch (SQLException ex) {
        Logger.getLogger(alterMenu.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pesanMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pesanMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pesanMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pesanMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pesanMenu().setVisible(true);
            }
        });

        
    }
     private void tampilkan() {
       int row=menuTable.getRowCount();
       for(int a=0; a<row; a++){
           model.removeRow(0);
       }
    try{
        Connection cn= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/restoran","root","");
        ResultSet rs=cn.createStatement().executeQuery ("Select * from log_pesan");
        while(rs.next()){
            String data[]={rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(5),rs.getString(6)};
            model.addRow(data);
        }
    } catch (SQLException ex) {
        Logger.getLogger (pesanMenu.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
 
     private void kembali() {
        pesanMenu ad = new pesanMenu();
        ad.setVisible(true);
        dispose();
    }
     
    private void clear(){
        txtID.setText("");
        txtNamaMenu.setText("");
        txtHarga.setText("");
        txtJumlah.setText("");
    }
    
    
    private void tampilkan1() {
       int row=menuTable1.getRowCount();
       for(int a=0; a<row; a++){
           model1.removeRow(0);
       }
    try{
        Connection cn= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/restoran","root","");
        ResultSet rs=cn.createStatement().executeQuery ("Select * from menu");
        while(rs.next()){
            String data[]={rs.getString(1),rs.getString(2),rs.getString(3)};
            model1.addRow(data);
        }
    } catch (SQLException ex) {
        Logger.getLogger (alterMenu.class.getName()).log(Level.SEVERE, null, ex);
    }
}
private void tampilkan2() {
       int row=tblAntrian.getRowCount();
       for(int a=0; a<row; a++){
           model2.removeRow(0);
       }
    try{
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost/restoran","root","");
        Statement st = con.createStatement();
        String searchQuery = "SELECT * FROM log_pesan WHERE status = 'Di Dapur' ORDER BY kd_pesanan ASC";
        ResultSet rs = st.executeQuery(searchQuery);
        while(rs.next()){
            String data[]={rs.getString(1),rs.getString(2),rs.getString(3)};
            model2.addRow(data);
        }
    } catch (SQLException ex) {
        Logger.getLogger (alterMenu.class.getName()).log(Level.SEVERE, null, ex);
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bayarNow;
    private javax.swing.JButton cekMenu;
    private javax.swing.JButton cekNama;
    private javax.swing.JLabel diskon;
    private javax.swing.JLabel harga;
    private javax.swing.JLabel hargaKirim;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelHarga;
    private javax.swing.JLabel labelHarga1;
    private javax.swing.JLabel labelHarga2;
    private javax.swing.JLabel labelHarga3;
    private javax.swing.JLabel labelHarga4;
    private javax.swing.JLabel labelHarga5;
    private javax.swing.JTable menuTable;
    private javax.swing.JTable menuTable1;
    private javax.swing.JLabel ongkir;
    private javax.swing.JLabel ongkir1;
    private javax.swing.JLabel ongkir2;
    private javax.swing.JTable tblAntrian;
    private javax.swing.JButton tmbhPesanan;
    private javax.swing.JLabel totalharga;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtNamaMenu;
    private javax.swing.JTextField txtPemesan;
    private javax.swing.JTextField uang;
    // End of variables declaration//GEN-END:variables
}
