/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restoran_alstruk;

import java.sql.Connection;
import restoran_alstruk.login;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Akhmad
 */
public class register extends javax.swing.JFrame {
    Connection con = null;
    Statement st = null;
    /**
     * Creates new form register
     */
    public register() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    private void hapuslayar(){
        username.setText("");
        pass.setText("");
        nama.setText("");
        notelp.setText("");
        alamat.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        username = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        backLogin = new javax.swing.JButton();
        pass = new javax.swing.JPasswordField();
        regisbtn = new javax.swing.JButton();
        alamat = new javax.swing.JTextField();
        notelp = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        username.setBorder(null);
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 152, 260, 30));

        nama.setBorder(null);
        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 260, 30));

        backLogin.setFont(new java.awt.Font("Montserrat SemiBold", 0, 11)); // NOI18N
        backLogin.setActionCommand("regisBtn");
        backLogin.setBorder(null);
        backLogin.setBorderPainted(false);
        backLogin.setContentAreaFilled(false);
        backLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backLoginActionPerformed(evt);
            }
        });
        getContentPane().add(backLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 610, 60, 30));

        pass.setBorder(null);
        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        getContentPane().add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 242, 260, 30));

        regisbtn.setFont(new java.awt.Font("Montserrat SemiBold", 0, 11)); // NOI18N
        regisbtn.setActionCommand("regisBtn");
        regisbtn.setBorder(null);
        regisbtn.setBorderPainted(false);
        regisbtn.setContentAreaFilled(false);
        regisbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        regisbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regisbtnActionPerformed(evt);
            }
        });
        getContentPane().add(regisbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 580, 90, 20));

        alamat.setBorder(null);
        alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamatActionPerformed(evt);
            }
        });
        getContentPane().add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 510, 260, 50));

        notelp.setBorder(null);
        getContentPane().add(notelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 422, 260, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/daptar.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void backLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backLoginActionPerformed
                // TODO add your handling code here:
       
        this.setVisible(false);
        new login().setVisible(true);
    }//GEN-LAST:event_backLoginActionPerformed

    private void regisbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regisbtnActionPerformed
        try {
            if(username.getText().equals("") ||
            pass.getPassword().equals("") ||
            nama.getText().equals("")){   
            JOptionPane.showMessageDialog(this, "Data Tidak Boleh Kosong", "Pesan", JOptionPane.ERROR_MESSAGE);
            hapuslayar();
            }else{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con=DriverManager.getConnection("jdbc:mysql://localhost/restoran","root","");
                String simpan = "INSERT INTO admin (username,pass,nama_lengkap,notelp,alamat) VALUES('"+username.getText()+"','"+String.valueOf(pass.getPassword())+"','"+nama.getText()+"','"+notelp.getText()+"','"+alamat.getText()+"')";
                st=con.createStatement();
                int SA = st.executeUpdate(simpan);
                JOptionPane.showMessageDialog(null, "Registrasi Berhasil");
                this.setVisible(false);
                new login().setVisible(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"This Account is Already exist / Duplicate Account ", "Pesan",JOptionPane.WARNING_MESSAGE);
            hapuslayar();
        }
    }//GEN-LAST:event_regisbtnActionPerformed

    private void alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamatActionPerformed

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JButton backLogin;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField notelp;
    private javax.swing.JPasswordField pass;
    private javax.swing.JButton regisbtn;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
